window.QUAL_A_BOA_DATA = {
  "atualizado_em": "2026-09-16T21:06-03:00",
  "eventos": [
    {
      "id": 19,
      "nome": "Aberto para bate-papo e encontros + chope em dobro",
      "categoria": "gastronomia",
      "data_inicio": "2026-09-15",
      "data_fim": "2026-09-16",
      "hora_inicio": null,
      "hora_fim": "20:00",
      "local": "Bugio Trindade",
      "endereco": "Bugio Trindade, Servidão Cristiano Wanderley Faria, 25, Trindade, Florianópolis - SC, 88040-405, Brasil",
      "bairro": "Trindade",
      "descricao": "Casa aberta para encontros com promoção de chopes e drinks em dobro até as 20h.",
      "lat": -27.59661,
      "lng": -48.52273,
      "instagram_url": "https://www.instagram.com/p/DdO5voUlfwI/",
      "foto": ""
    },
    {
      "id": 20,
      "nome": "O canto do Sabiá",
      "categoria": "musica",
      "data_inicio": "2026-09-17",
      "data_fim": "2026-09-17",
      "hora_inicio": "20:30",
      "hora_fim": null,
      "local": "Bugio Trindade",
      "endereco": "Bugio Trindade, Servidão Cristiano Wanderley Faria, 25, Trindade, Florianópolis - SC, 88040-405, Brasil",
      "bairro": "Trindade",
      "descricao": "Apresentação de Mixa e Ian Fabris com o projeto O canto do Sabiá.",
      "lat": -27.59661,
      "lng": -48.52273,
      "instagram_url": "https://www.instagram.com/p/DdO5voUlfwI/",
      "foto": ""
    },
    {
      "id": 21,
      "nome": "Noite paraense com Banzeiro da Magia",
      "categoria": "musica",
      "data_inicio": "2026-09-18",
      "data_fim": "2026-09-18",
      "hora_inicio": "20:30",
      "hora_fim": null,
      "local": "Bugio Trindade",
      "endereco": "Bugio Trindade, Servidão Cristiano Wanderley Faria, 25, Trindade, Florianópolis - SC, 88040-405, Brasil",
      "bairro": "Trindade",
      "descricao": "Show com repertório de ritmos amazônicos e paraenses.",
      "lat": -27.59661,
      "lng": -48.52273,
      "instagram_url": "https://www.instagram.com/p/DdO5voUlfwI/",
      "foto": ""
    },
    {
      "id": 22,
      "nome": "Forró do Mancusi",
      "categoria": "musica",
      "data_inicio": "2026-09-19",
      "data_fim": "2026-09-19",
      "hora_inicio": "20:30",
      "hora_fim": null,
      "local": "Bugio Trindade",
      "endereco": "Bugio Trindade, Servidão Cristiano Wanderley Faria, 25, Trindade, Florianópolis - SC, 88040-405, Brasil",
      "bairro": "Trindade",
      "descricao": "Baile com Rodrigo Mancusi e repertório de forró e música nordestina.",
      "lat": -27.59661,
      "lng": -48.52273,
      "instagram_url": "https://www.instagram.com/p/DdO5voUlfwI/",
      "foto": ""
    },
    {
      "id": 30,
      "nome": "9º Encontro Nacional e Internacional de Mulheres na roda de samba - Florianópolis",
      "categoria": "musica",
      "data_inicio": "2026-09-26",
      "data_fim": "2026-09-26",
      "hora_inicio": "15:00",
      "hora_fim": "23:30",
      "local": "Bugio Trindade",
      "endereco": "Bugio Trindade, Servidão Cristiano Wanderley Faria, 25, Trindade, Florianópolis - SC, 88040-405, Brasil",
      "bairro": "Trindade",
      "descricao": "Encontro de mulheres na roda de samba com cantoras confirmadas em Florianópolis.",
      "lat": -27.59661,
      "lng": -48.52273,
      "instagram_url": "https://www.instagram.com/p/DdMdXJHDsOu/",
      "foto": ""
    },
    {
      "id": 37,
      "nome": "1º Festival Literário de Floripa",
      "categoria": "festivais",
      "data_inicio": "2026-09-19",
      "data_fim": "2026-09-19",
      "hora_inicio": "14:00",
      "hora_fim": "22:00",
      "local": "Rua Padre Lourenço Rodrigues de Andrade, 650, Santo Antônio de Lisboa, Florianópolis - SC, 88050-400, Brasil",
      "endereco": "Rua Padre Lourenço Rodrigues de Andrade, 650, Santo Antônio de Lisboa, Florianópolis - SC, 88050-400, Brasil",
      "bairro": "Santo Antônio de Lisboa",
      "descricao": "Festival literário com programação alterada para começar às 14h e seguir até às 22h.",
      "lat": -27.50676,
      "lng": -48.51878,
      "instagram_url": "https://www.instagram.com/p/DdKdnjwn7vd/",
      "foto": ""
    },
    {
      "id": 42,
      "nome": "Exposição \"Ressonâncias do Gesto\"",
      "categoria": "exposicoes",
      "data_inicio": "2026-09-11",
      "data_fim": "2026-09-17",
      "hora_inicio": null,
      "hora_fim": null,
      "local": "Fundação Cultural Badesc",
      "endereco": "Fundação Cultural Badesc, Rua Visconde de Ouro Preto, 216, Centro, Florianópolis - SC, 88020-040, Brasil",
      "bairro": "Centro",
      "descricao": "Mostra da artista visual Lena Peixer, em cartaz com entrada gratuita.",
      "lat": -27.59522,
      "lng": -48.54782,
      "instagram_url": "https://www.instagram.com/p/DdKANqAA8aC/",
      "foto": ""
    },
    {
      "id": 43,
      "nome": "1º Festival Literário de Florianópolis",
      "categoria": "festivais",
      "data_inicio": "2026-09-19",
      "data_fim": "2026-09-19",
      "hora_inicio": "14:00",
      "hora_fim": "20:00",
      "local": "Rua Padre Lourenço Rodrigues de Andrade, 650, Santo Antônio de Lisboa, Florianópolis - SC, 88050-400, Brasil",
      "endereco": "Rua Padre Lourenço Rodrigues de Andrade, 650, Santo Antônio de Lisboa, Florianópolis - SC, 88050-400, Brasil",
      "bairro": "Santo Antônio de Lisboa",
      "descricao": "Festival literário com lançamentos de livros, rodas de conversa, bingo literário e sarau poético.",
      "lat": -27.50676,
      "lng": -48.51878,
      "instagram_url": "https://www.instagram.com/p/DdKN32FKR6G/",
      "foto": ""
    },
    {
      "id": 44,
      "nome": "Show Brisas do Sul",
      "categoria": "musica",
      "data_inicio": "2026-09-19",
      "data_fim": "2026-09-19",
      "hora_inicio": "20:00",
      "hora_fim": null,
      "local": "Rua Padre Lourenço Rodrigues de Andrade, 650, Santo Antônio de Lisboa, Florianópolis - SC, 88050-400, Brasil",
      "endereco": "Rua Padre Lourenço Rodrigues de Andrade, 650, Santo Antônio de Lisboa, Florianópolis - SC, 88050-400, Brasil",
      "bairro": "Santo Antônio de Lisboa",
      "descricao": "Show musical com repertório voltado às raízes culturais, tradições e paisagens do sul do Brasil.",
      "lat": -27.50676,
      "lng": -48.51878,
      "instagram_url": "https://www.instagram.com/p/DdKN32FKR6G/",
      "foto": ""
    },
    {
      "id": 45,
      "nome": "Lançamento do livro \"Escandalizar Desertos\", de Andreia Dacoregio",
      "categoria": "encontros",
      "data_inicio": "2026-09-18",
      "data_fim": "2026-09-18",
      "hora_inicio": "18:00",
      "hora_fim": null,
      "local": "Fundação Cultural Badesc",
      "endereco": "Fundação Cultural Badesc, Rua Visconde de Ouro Preto, 216, Centro, Florianópolis - SC, 88020-040, Brasil",
      "bairro": "Centro",
      "descricao": "Lançamento do terceiro livro de poesia de Andreia Dacoregio, com entrada gratuita.",
      "lat": -27.59522,
      "lng": -48.54782,
      "instagram_url": "https://www.instagram.com/p/DdJ0fT7OJfP/",
      "foto": ""
    },
    {
      "id": 51,
      "nome": "Caça-brindes com QR codes espalhados pelos arredores da UFSC",
      "categoria": "feiras",
      "data_inicio": "2026-09-11",
      "data_fim": "2026-09-18",
      "hora_inicio": null,
      "hora_fim": null,
      "local": "UFSC",
      "endereco": "UFSC, Avenida Professor Henrique da Silva Fontes, Trindade, Florianópolis - SC, 88036-700, Brasil",
      "bairro": "Trindade",
      "descricao": "Jogo de caça-brindes com QR codes espalhados pelo campus para resgate de prêmios.",
      "lat": -27.59776,
      "lng": -48.51631,
      "instagram_url": "https://www.instagram.com/p/DdJUJtrFuS_/",
      "foto": ""
    },
    {
      "id": 55,
      "nome": "Programação de cinema no Cinesystem do Villa Romana Shopping",
      "categoria": "cinema_audiovisual",
      "data_inicio": "2026-09-10",
      "data_fim": "2026-09-16",
      "hora_inicio": null,
      "hora_fim": null,
      "local": "Cinesystem",
      "endereco": "Cinesystem, Avenida Madre Benvenuta, 687, Itacorubi, Florianópolis - SC, 88035-000, Brasil",
      "bairro": "Itacorubi",
      "descricao": "Programação de filmes de 10 a 16 de setembro no Cinesystem, com promoção de matinês e demais horários.",
      "lat": -27.5913,
      "lng": -48.51444,
      "instagram_url": "https://www.instagram.com/p/DdHAmy0kd7j/",
      "foto": ""
    },
    {
      "id": 64,
      "nome": "Oficina \"Introdução à Aquarela\" (segunda turma)",
      "categoria": "cursos_oficinas",
      "data_inicio": "2026-09-22",
      "data_fim": "2026-09-24",
      "hora_inicio": "14:00",
      "hora_fim": "17:00",
      "local": "Fundação Cultural Badesc",
      "endereco": "Fundação Cultural Badesc, Rua Visconde de Ouro Preto, 216, Centro, Florianópolis - SC, 88020-040, Brasil",
      "bairro": "Centro",
      "descricao": "Oficina de introdução à aquarela ministrada por Gabriela Luft, em dois encontros.",
      "lat": -27.59522,
      "lng": -48.54782,
      "instagram_url": "https://www.instagram.com/p/DdEqB8jjul_/",
      "foto": ""
    },
    {
      "id": 67,
      "nome": "Thiago Di Luca apresenta: Forró de Manezinho para crianças",
      "categoria": "musica",
      "data_inicio": "2026-09-27",
      "data_fim": "2026-09-27",
      "hora_inicio": "15:00",
      "hora_fim": null,
      "local": "Bugio Trindade",
      "endereco": "Bugio Trindade, Servidão Cristiano Wanderley Faria, 25, Trindade, Florianópolis - SC, 88040-405, Brasil",
      "bairro": "Trindade",
      "descricao": "Show musical infantil interativo com Thiago Di Luca e banda.",
      "lat": -27.59661,
      "lng": -48.52273,
      "instagram_url": "https://www.instagram.com/p/DdC4KCNMhcF/",
      "foto": ""
    },
    {
      "id": 77,
      "nome": "Antropomórfico: Cavernas de Sentimentos Omitidos",
      "categoria": "exposicoes",
      "data_inicio": "2026-09-08",
      "data_fim": "2026-10-03",
      "hora_inicio": "18:00",
      "hora_fim": "00:00",
      "local": "Galeria Lama",
      "endereco": "Galeria Lama, Calçadão João Pinto, Centro, Florianópolis - SC, 88010-420, Brasil",
      "bairro": "Centro",
      "descricao": "Exposição de Saturno Talavera com abertura em 8 de setembro.",
      "lat": -27.59951,
      "lng": -48.54873,
      "instagram_url": "https://www.instagram.com/p/DdCTF1ZEbNJ/",
      "foto": ""
    },
    {
      "id": 79,
      "nome": "Desdobramentos da Transmutação",
      "categoria": "exposicoes",
      "data_inicio": "2026-09-10",
      "data_fim": "2026-09-24",
      "hora_inicio": "19:00",
      "hora_fim": "19:00",
      "local": "Rua Doutor Jorge da Luz Fontes, 310, Centro, Florianópolis - SC, 88020-185, Brasil",
      "endereco": "Rua Doutor Jorge da Luz Fontes, 310, Centro, Florianópolis - SC, 88020-185, Brasil",
      "bairro": "Centro",
      "descricao": "Exposição de Larissa Arpana com abertura em 10 de setembro.",
      "lat": -27.60293,
      "lng": -48.54749,
      "instagram_url": "https://www.instagram.com/p/DdCTF1ZEbNJ/",
      "foto": ""
    },
    {
      "id": 96,
      "nome": "Feira de Publicações Coletivo Elza",
      "categoria": "feiras",
      "data_inicio": "2026-09-19",
      "data_fim": "2026-09-19",
      "hora_inicio": "11:00",
      "hora_fim": "19:00",
      "local": "Rua Padre Lourenço Rodrigues de Andrade, 650, Santo Antônio de Lisboa, Florianópolis - SC, 88050-400, Brasil",
      "endereco": "Rua Padre Lourenço Rodrigues de Andrade, 650, Santo Antônio de Lisboa, Florianópolis - SC, 88050-400, Brasil",
      "bairro": "Santo Antônio de Lisboa",
      "descricao": "Feira de publicações dentro da programação do 1º Festival Literário de Florianópolis.",
      "lat": -27.50676,
      "lng": -48.51878,
      "instagram_url": "https://www.instagram.com/p/Dc9ejjWKfE2/",
      "foto": ""
    },
    {
      "id": 111,
      "nome": "Oficina “Imagens que criam mundos: narrativas da paisagem, do amor e das ausências na história da arte”",
      "categoria": "cursos_oficinas",
      "data_inicio": "2026-08-01",
      "data_fim": "2026-09-30",
      "hora_inicio": null,
      "hora_fim": null,
      "local": "Fundação Cultural Badesc",
      "endereco": "Fundação Cultural Badesc, Rua Visconde de Ouro Preto, 216, Centro, Florianópolis - SC, 88020-040, Brasil",
      "bairro": "Centro",
      "descricao": "Oficina ministrada por Marlen De Martino realizada durante os meses de agosto e setembro.",
      "lat": -27.59522,
      "lng": -48.54782,
      "instagram_url": "https://www.instagram.com/p/Dc4WzeMDuPd/",
      "foto": ""
    },
    {
      "id": 117,
      "nome": "Do Lado Avesso – O bordado como instrumento subversivo",
      "categoria": "cursos_oficinas",
      "data_inicio": "2026-09-19",
      "data_fim": "2026-09-19",
      "hora_inicio": "13:00",
      "hora_fim": null,
      "local": "Bugio Centro (Centro Bugio)",
      "endereco": "Bugio Centro, Rua Victor Meirelles, 112, Centro, Florianópolis - SC, 88010-440, Brasil",
      "bairro": "Centro",
      "descricao": "Oficina de bordado com Luana Lopes.",
      "lat": -27.59852,
      "lng": -48.54884,
      "instagram_url": "https://www.instagram.com/p/Dc4GqNLEaxO/",
      "foto": ""
    },
    {
      "id": 118,
      "nome": "Canecas Criativas em Cerâmica",
      "categoria": "cursos_oficinas",
      "data_inicio": "2026-09-19",
      "data_fim": "2026-09-19",
      "hora_inicio": "14:00",
      "hora_fim": null,
      "local": "Bugio Centro",
      "endereco": "Bugio Centro, Rua Victor Meirelles, 112, Centro, Florianópolis - SC, 88010-440, Brasil",
      "bairro": "Centro",
      "descricao": "Oficina de cerâmica com Thaís Dutra.",
      "lat": -27.59852,
      "lng": -48.54884,
      "instagram_url": "https://www.instagram.com/p/Dc4GqNLEaxO/",
      "foto": ""
    },
    {
      "id": 119,
      "nome": "Aulão Gratuito de Forró",
      "categoria": "musica",
      "data_inicio": "2026-09-25",
      "data_fim": "2026-09-25",
      "hora_inicio": null,
      "hora_fim": null,
      "local": "Bugio Centro",
      "endereco": "Bugio Centro, Rua Victor Meirelles, 112, Centro, Florianópolis - SC, 88010-440, Brasil",
      "bairro": "Centro",
      "descricao": "Aulão gratuito de forró com Prof. Baby Trindade.",
      "lat": -27.59852,
      "lng": -48.54884,
      "instagram_url": "https://www.instagram.com/p/Dc4GqNLEaxO/",
      "foto": ""
    },
    {
      "id": 120,
      "nome": "Oficina de Carimbos Monstruosos para Crianças",
      "categoria": "cursos_oficinas",
      "data_inicio": "2026-09-26",
      "data_fim": "2026-09-26",
      "hora_inicio": "13:00",
      "hora_fim": null,
      "local": "Rua Victor Meirelles, 112, Centro, Florianópolis - SC, 88010-440, Brasil",
      "endereco": "Rua Victor Meirelles, 112, Centro, Florianópolis - SC, 88010-440, Brasil",
      "bairro": "Centro",
      "descricao": "Oficina de carimbos para crianças com Marceli Mengarda.",
      "lat": -27.59852,
      "lng": -48.54884,
      "instagram_url": "https://www.instagram.com/p/Dc4GqNLEaxO/",
      "foto": ""
    },
    {
      "id": 121,
      "nome": "Oficina de Crochê",
      "categoria": "cursos_oficinas",
      "data_inicio": "2026-09-26",
      "data_fim": "2026-09-26",
      "hora_inicio": "13:30",
      "hora_fim": null,
      "local": "Rua Victor Meirelles, 112, Centro, Florianópolis - SC, 88010-440, Brasil",
      "endereco": "Rua Victor Meirelles, 112, Centro, Florianópolis - SC, 88010-440, Brasil",
      "bairro": "Centro",
      "descricao": "Oficina de crochê com Maiara (Lala).",
      "lat": -27.59852,
      "lng": -48.54884,
      "instagram_url": "https://www.instagram.com/p/Dc4GqNLEaxO/",
      "foto": ""
    },
    {
      "id": 122,
      "nome": "Laboratório de Impressão 3D",
      "categoria": "encontros",
      "data_inicio": "2026-09-26",
      "data_fim": "2026-09-26",
      "hora_inicio": "13:00",
      "hora_fim": null,
      "local": "Bugio Centro",
      "endereco": "Bugio Centro, Rua Victor Meirelles, 112, Centro, Florianópolis - SC, 88010-440, Brasil",
      "bairro": "Centro",
      "descricao": "Laboratório de impressão 3D com Luli e Mau.",
      "lat": -27.59852,
      "lng": -48.54884,
      "instagram_url": "https://www.instagram.com/p/Dc4GqNLEaxO/",
      "foto": ""
    }
  ]
};
